###########################
# DebugFlag
###########################

[[Headline]]
name = "hl-debug"
text = "DebugFlag"
pos = { x = 10, y = 40 }

[[CheckBox]]
name = "draw-collider"
label = "DrawCollider"
pos = { x = 10, y = 80 }
default = false

[[CheckBox]]
name = "draw-map-collider"
label = "DrawMapCollider"
pos = { x = 10, y = 110 }
default = false

[[CheckBox]]
name = "log-effect-num"
label = "LogEffectNum"
pos = { x = 10, y = 140 }
default = false

[[CheckBox]]
name = "log-decor-num"
label = "LogDecorNum"
pos = { x = 10, y = 170 }
default = false

###########################
# Shader
###########################

[[Headline]]
name = "hl-shader"
text = "Shader"
pos = { x = 250, y = 40 }

[[CheckBox]]
name = "disable-light"
label = "DisableLight"
pos = { x = 250, y = 80 }
default = false

[[CheckBox]]
name = "disable-distortion"
label = "DisableDistortion"
pos = { x = 250, y = 110 }
default = false

###########################
# FPS
###########################

[[Headline]]
name = "hl-FPS"
text = "FPS"
pos = { x = 490, y = 40 }
width = 100

[[CheckBox]]
name = "cb-fix-fps"
label = "固定フレーム"
pos = { x = 490, y = 80 }
default = false

[[Slider]]
name = "sl-fps"
pos = { x = 490, y = 110 }
label = "FPS"
default = 60
min = 10.0
max = 120.0
enabled = false