[Slime]
basePos = "(-260, -40)"
periodicSec = 1.3
jumpSec = 1.0

[Text]
basePos = "(-220, -54)"
offsetX = 1
periodicSec = 3.9
jumpPeriodicOffset = -0.15
jumpIndexCoef = 15.0
jumpTimeRate = 0.2
jumpHeight = 20
rotatePeriodicOffset = -1.3
rotateIndexCoef = 8.0
rotateTimeRate = 0.2

[ProgressBar]
basePos = "(-220, -25)"
size = "(200, 5)"
