[Base]
hp = 12
pivot = "(0, -15)"
colRadius = 18

[Move]
gravity = 400
jumpHeight = 300
maxSpeedY = 110
decelX = 20
moveX = 200
fallLimitOffs = 50

[[Convene.Baby]]
waitTimeSec = 1.5
offset = "(-200, -400)"
appearTime = 3.0
appearMove = "(0, 450)"

[[Convene.Baby]]
waitTimeSec = 0.5
offset = "(200, -400)"
appearTime = 4.0
appearMove = "(0, 600)"

