[Base]
hp = 12
pivot = "(0, -15)"
colRadius = 18

[Move]
gravity = 400
jumpHeight = 300
maxSpeedY = 95
decelX = 30
moveX = 200
chargeTimeSec = 0.9
chargeOffs = 60

[[Convene.Baby]]
waitTimeSec = 1.5
offset = "(-200, -400)"
appearTime = 3.0
appearMove = "(0, 450)"

[[Convene.Baby]]
waitTimeSec = 0.5
offset = "(200, -400)"
appearTime = 4.0
appearMove = "(0, 600)"

