[Base]
hp = 160
eyeL = "(108, 155)"
eyeR = "(-117, 153)"
mouthPos = "(-20, 280)"
pivot = "(0, 210)"
colSize = "(360, 380)"
mainColliders=[
  "((-245, 0), (-315, 105), (-130, 35))",
  "((-160, 25), (-235, 200), (200, 155))",
  "((-235, 200), (-300, 400), (200, 155))",
  "((215, 400), (-300, 400), (200, 155))",
  "((200, 155), (225, 170), (205, 240))",
  "((280, 270), (225, 170), (205, 240))"
]
crownColliders=[
  "((-265, -10), (225, 170), (350, 0))",
  "((-265, -10), (350, -180), (350, 0))",
  "((-265, -10), (350, -180), (300, -245))",
  "((-265, -10), (230, -280), (300, -245))",
  "((-265, -10), (-300, -212), (221, -275))",
  "((-170, -350), (-300, -212), (221, -275))",
  "((-170, -350), (90, -350), (221, -275))",
]
terrain = "(-180, -350, 380, 750)"

[Eye]
distRate = 0.25
erpRate = 0.02
damageErpRate = 0.5
limitBeginL = "(-60, 5)"
limitEndL = "(62, -15)"
limitBeginR = "(-61, -18)"
limitEndR = "(62, 12)"

[Foot]
animTimeSec = 5.0
animFrameMap = [
  8,
  7, 7,
  6, 6,
  5, 5,
  4, 4,
  5, 5,
  6, 6,
  7, 7,
  8, 8,
  7, 7,
  6, 6,
  5, 5,
  4, 4,
  3, 3,
  2, 2,
  1, 1,
  0
]

[Foot.Foot1]
pos = "(-350, 260)"
animTimeOffset = 0
rotateDeg = 0
isFlip = false

[Foot.Foot2]
pos = "(140, 310)"
animTimeOffset = 2.5
rotateDeg = 0
isFlip = false

[Foot.Foot3]
pos = "(280, 200)"
animTimeOffset = 1.7
rotateDeg = 120
isFlip = false

[Foot.Foot4]
pos = "(-200, -100)"
animTimeOffset = 1.25
rotateDeg = 0
isFlip = true

[Shout]
radius = 900
power = 200
time = 3.5
count = 1